USE cura;

CREATE TABLE Conditions (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(40) NOT NULL,
    description text,
    PRIMARY KEY (id)
    );

INSERT INTO Conditions(name, description) VALUES ('Allergies', 'Allergies occur when your immune system reacts to a foreign substance — such as pollen, bee venom or pet dander — that doesn\'t cause a reaction in most people. When you come into contact with the allergen, your immune system\'s reaction can inflame your skin, sinuses, airways or digestive system. The severity of allergies varies from person to person and can range from minor irritation to anaphylaxis — a potentially life-threatening emergency. While most allergies can\'t be cured, a number of treatments can help relieve your allergy symptoms.');
INSERT INTO Conditions(name, description) VALUES ('Alzheimer\'s Disease', 'Alzheimer\'s disease is a progressive disease that destroys memory and other important mental functions. At first, someone with Alzheimer\'s disease may notice mild confusion and difficulty remembering. Eventually, people with the disease may even forget important people in their lives and undergo dramatic personality changes. Current Alzheimer\'s disease medications and management strategies may temporarily improve symptoms. This can sometimes help people with Alzheimer\'s disease maximize function and maintain independence for a little while longer. But because there\'s no cure for Alzheimer\'s disease, it\'s important to seek supportive services and tap into your support network as early as possible.');
INSERT INTO Conditions(name, description) VALUES ('Anemia', 'Anemia is a condition in which you don\’t have enough healthy red blood cells to carry adequate oxygen to the body\’s tissues. Having anemia may make you feel tired and weak. Anemia can be temporary or long term, and it can range from mild to severe. Treatments for anemia range from taking supplements to undergoing medical procedures.');
INSERT INTO Conditions(name, description) VALUES ('Arthritis', 'Arthritis is inflammation of one or more of your joints. The main symptoms of arthritis are joint pain and stiffness, which typically worsen with age. Treatments vary depending on the type of arthritis. The main goals of arthritis treatments are to reduce symptoms and improve quality of life.');
INSERT INTO Conditions(name, description) VALUES ('Asthma', 'Asthma is a condition in which your airways narrow and swell and produce extra mucus. This can make breathing difficult and trigger coughing, wheezing and shortness of breath. Asthma can\’t be cured, but its symptoms can be controlled. Because asthma often changes over time, it\’s important that you work with your doctor to track your signs and symptoms and adjust treatment as needed.');
INSERT INTO Conditions(name, description) VALUES ('Brain Tumor', 'A brain tumor is a mass or growth of abnormal cells in your brain or close to your brain. Many different types of brain tumors exist. Some brain tumors are noncancerous (benign), and some brain tumors are cancerous (malignant). Brain tumors can begin in your brain (primary brain tumors), or cancer can begin in other parts of your body and spread to your brain (secondary, or metastatic, brain tumors). Brain tumor treatment options depend on the type of brain tumor you have, as well as its size and location.');
INSERT INTO Conditions(name, description) VALUES ('Cataracts', 'A cataract is a clouding of the normally clear lens of your eye. For people who have cataracts, seeing through cloudy lenses is a bit like looking through a frosty or fogged-up window. Most cataracts develop slowly and don\’t disturb your eyesight early on. But with time, cataracts will eventually interfere with your vision. At first, stronger lighting and eyeglasses can help you deal with cataracts. But if impaired vision interferes with your usual activities, you might need cataract surgery. Fortunately, cataract surgery is generally a safe, effective procedure.');
INSERT INTO Conditions(name, description) VALUES ('Coronary Artery Disease (CAD)', 'Coronary artery disease develops when the major blood vessels that supply your heart with blood, oxygen and nutrients (coronary arteries) become damaged or diseased. Cholesterol-containing deposits (plaque) in your arteries and inflammation are usually to blame for coronary artery disease. When plaque builds up, they narrow your coronary arteries, decreasing blood flow to your heart. Eventually, the decreased blood flow may cause chest pain (angina), shortness of breath, or other coronary artery disease signs and symptoms. A complete blockage can cause a heart attack.');
INSERT INTO Conditions(name, description) VALUES ('Depression', 'Depression is a mood disorder that causes a persistent feeling of sadness and loss of interest. Also called major depressive disorder or clinical depression, it affects how you feel, think and behave and can lead to a variety of emotional and physical problems. You may have trouble doing normal day-to-day activities, and sometimes you may feel as if life isn\’t worth living. Depression may require long-term treatment. Most people with depression feel better with medication, psychological counseling, or both.');
INSERT INTO Conditions(name, description) VALUES ('Diabetes', 'Diabetes mellitus refers to a group of diseases that affect how your body uses blood sugar (glucose). Glucose is an important source of energy for the cells that make up your muscles and tissues and it\’s also your brain\’s main source of fuel. Having diabetes means having too much glucose in your blood, although the causes may differ.');
INSERT INTO Conditions(name, description) VALUES ('Ear Infection', 'An ear infection (acute otitis media) is most often a bacterial or viral infection that affects the middle ear, the air-filled space behind the eardrum that contains the tiny vibrating bones of the ear. Children are more likely than adults to get ear infections. Ear infections frequently are painful because of inflammation and buildup of fluids in the middle ear.');
INSERT INTO Conditions(name, description) VALUES ('Eczema (Atopic Dermatitis)', 'Atopic dermatitis (eczema) is a condition that makes your skin red and itchy. It\’s common in children but can occur at any age. Atopic dermatitis is long lasting (chronic) and tends to flare periodically and then subside. It may be accompanied by asthma or hay fever. No cure has been found for atopic dermatitis. But treatments and self-care measures can relieve itching and prevent new outbreaks.');
INSERT INTO Conditions(name, description) VALUES ('Gout', 'Gout is characterized by sudden, severe attacks of pain, redness and tenderness in joints, often the joint at the base of the big toe. Men are more likely to get gout, but women become increasingly susceptible to gout after menopause. An attack of gout can occur suddenly, often waking you up in the middle of the night with the sensation that your big toe is on fire. The affected joint is hot, swollen and so tender that even the weight of the sheet on it may seem intolerable.');
INSERT INTO Conditions(name, description) VALUES ('Gum Disease (Periodontal Disease)', 'Periodontitis is a serious gum infection that damages the soft tissue and destroys the bone that supports your teeth. Periodontitis can cause tooth loss or worse, an increased risk of heart attack or stroke and other serious health problems. Periodontitis is common but largely preventable. Periodontitis is usually the result of poor oral hygiene. Brushing at least twice a day, flossing daily and getting regular dental checkups can greatly reduce your chance of developing periodontitis.');
INSERT INTO Conditions(name, description) VALUES ('Hepatitis', 'Hepatitis is an inflammation of the liver. The condition can be self-limiting or can progress to fibrosis (scarring), cirrhosis or liver cancer. Hepatitis viruses are the most common cause of hepatitis in the world but other infections, toxic substances (e.g. alcohol, certain drugs), and autoimmune diseases can also cause hepatitis.');
INSERT INTO Conditions(name, description) VALUES ('HIV/AIDS', 'Acquired immunodeficiency syndrome (AIDS) is a chronic, potentially life-threatening condition caused by the human immunodeficiency virus (HIV). By damaging your immune system, HIV interferes with your body\’s ability to fight the organisms that cause disease. HIV is a sexually transmitted infection. It can also be spread by contact with infected blood or from mother to child during pregnancy, childbirth or breastfeeding. Without medication, it may take years before HIV weakens your immune system to the point that you have AIDS. There\’s no cure for HIV/AIDS, but there are medications that can dramatically slow the progression of the disease.');
INSERT INTO Conditions(name, description) VALUES ('Irritable Bowel Syndrome', 'Irritable bowel syndrome (IBS) is a common disorder that affects the large intestine (colon). Irritable bowel syndrome commonly causes cramping, abdominal pain, bloating, gas, diarrhea and constipation. IBS is a chronic condition that you will need to manage long term.');
INSERT INTO Conditions(name, description) VALUES ('Kidney Stones', 'Kidney stones (renal lithiasis, nephrolithiasis) are small, hard mineral deposits that form inside your kidneys. The stones are made of mineral and acid salts. Kidney stones have many causes and can affect any part of your urinary tract — from your kidneys to your bladder. Often, stones form when the urine becomes concentrated, allowing minerals to crystallize and stick together.');
INSERT INTO Conditions(name, description) VALUES ('Leukemia', 'Leukemia is cancer of the body\’s blood-forming tissues, including the bone marrow and the lymphatic system. Leukemia usually involves the white blood cells. Your white blood cells are potent infection fighters — they normally grow and divide in an orderly way, as your body needs them. But in people with leukemia, the bone marrow produces abnormal white blood cells, which don\’t function properly.');
INSERT INTO Conditions(name, description) VALUES ('Lung Cancer', 'Lung cancer is a type of cancer that begins in the lungs. People who smoke have the greatest risk of lung cancer. The risk of lung cancer increases with the length of time and number of cigarettes you\’ve smoked. If you quit smoking, even after smoking for many years, you can significantly reduce your chances of developing lung cancer.');
INSERT INTO Conditions(name, description) VALUES ('Meningitis', 'Meningitis is an inflammation of the membranes (meninges) surrounding your brain and spinal cord. The swelling from meningitis typically triggers symptoms such as headache, fever and a stiff neck. Most cases of meningitis are caused by a viral infection, but bacterial and fungal infections are other causes. Seek immediate medical care if you suspect that you have meningitis. Early treatment of bacterial meningitis can prevent serious complications.');
INSERT INTO Conditions(name, description) VALUES ('Pneumonia', 'Pneumonia is an infection that inflames the air sacs in one or both lungs. The air sacs may fill with fluid or pus (purulent material), causing cough with phlegm or pus, fever, chills, and difficulty breathing. A variety of organisms, including bacteria, viruses and fungi, can cause pneumonia.');
INSERT INTO Conditions(name, description) VALUES ('Strep Throat', 'Strep throat is a bacterial infection that can make your throat feel sore and scratchy. If untreated, strep throat can cause complications, such as kidney inflammation or rheumatic fever. Strep throat is most common in children, but it affects people of all ages. If you or your child has signs or symptoms of strep throat, see your doctor for prompt testing and treatment.');
INSERT INTO Conditions(name, description) VALUES ('Stroke', 'A stroke occurs when the blood supply to part of your brain is interrupted or severely reduced, depriving brain tissue of oxygen and nutrients. Within minutes, brain cells begin to die. A stroke is a medical emergency. Prompt treatment is crucial. Early action can minimize brain damage and potential complications.');
INSERT INTO Conditions(name, description) VALUES ('Urinary Tract Infection', 'A urinary tract infection (UTI) is an infection in any part of your urinary system — your kidneys, ureters, bladder and urethra. Most infections involve the lower urinary tract — the bladder and the urethra. Women are at greater risk of developing a UTI than men are. Infection limited to your bladder can be painful and annoying. However, serious consequences can occur if a UTI spreads to your kidneys. Doctors typically treat urinary tract infections with antibiotics.');